workflows:
  android-workflow:
    name: Build HealthWay APK
    max_build_duration: 30
    environment:
      flutter: 3.19.0
      xcode: latest
      android: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
